#!/bin/bash

xrdb -merge .Xresources
xpmroot ~/background.xpm &

# system tray
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --widthtype percent --width 8 --transparent true --tint 0x000000 --alpha 0 --height 21 &

# screensaver
xscreensaver -no-splash &

# set the cursoe as pointer, otherwise X will appear as cursor
xsetroot -cursor_name left_ptr

# network manager applet
if [ -x /usr/bin/nm-applet ]; then
    nm-applet --sm-disable &
fi

if [ -x /usr/bin/volti ]; then
    volti &
fi

# Set background image with feh
# feh --bg-scale /usr/share/backgrounds/warty-final-ubuntu.png &

# start clipboard manager without icon
parcellite &

# let me go ahead with pre starting some of the apps
kuaipan4uk &


# fixed java application problem
export _JAVA_AWT_WM_NONREPARENTING=1

xmonad

