#!/bin/bash

xrdb -merge .Xresources
xpmroot ~/background.xpm &

# system tray
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --widthtype percent --width 5 --transparent true --tint 0x000000 --height 20 &

# screensaver
xscreensaver -no-splash &

# set the cursoe as pointer, otherwise X will appear as cursor
xsetroot -cursor_name left_ptr

# start clipboard manager without icon
# parcellite &

# let me go ahead with pre starting some of the apps
kuaipan4uk &


xmonad
