#!/bin/bash

xrdb -merge ~/.xmonad/.Xresources

xpmroot ~/background.xpm &

# system tray
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --widthtype percent --width 10 --transparent true --tint 0x000000 --alpha 0 --height 20 &

# screensaver
xscreensaver -no-splash &

# power-manager
xfce4-power-manager &

# set the cursoe as pointer, otherwise X will appear as cursor
xsetroot -cursor_name left_ptr

# network manager applet
if [ -x /usr/bin/nm-applet ]; then
    nm-applet --sm-disable &
fi

if [ -x /usr/bin/volti ]; then
    volti &
fi

# Set background image with feh
feh --bg-scale ~/Pictures/wallpaper.jpg &

# call bing wallpaper
bingwallpaper 1 &

# start clipboard manager without icon
parcellite &

# let me go ahead with pre starting some of the apps
owncloud &


# fixed java application problem
export _JAVA_AWT_WM_NONREPARENTING=1

xmonad

